name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: dockerfile/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          starcroft/poctest:1.1
          ghcr.io/starcroft/poctest:1.1
      
